import fs from 'node:fs';import path from 'node:path';import {handle,session,csrfCheck,json,fail,body,Failure} from '../server/studio-security.mjs';import {config} from '../server/studio-config.mjs';import {identity,head,snapshot,readFile} from '../server/studio-github.mjs';import {loadBundle,references,mediaPath,saveBundle} from '../server/studio-content.mjs';
const editorFile=()=>{const candidates=[path.join(process.cwd(),'tools','site-customizer-cloud.html'),new URL('../tools/site-customizer-cloud.html',import.meta.url),new URL('../../tools/site-customizer-cloud.html',import.meta.url)];for(const candidate of candidates){try{if(typeof candidate==='string'&&fs.existsSync(candidate))return candidate;if(candidate instanceof URL&&fs.existsSync(candidate))return candidate}catch{}}fail(500,'EDITOR_FILE','تعذر تحميل واجهة Studio على Netlify. تأكد من نشر tools/site-customizer-cloud.html ضمن ملفات Function.')};
const loginPage=()=>`<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>دخول استوديو جسر الشرق</title><style>body{margin:0;min-height:100vh;display:grid;place-items:center;background:#f4f8fc;color:#16314d;font:17px/1.9 system-ui}main{max-width:430px;margin:24px;padding:40px;background:white;border:1px solid #deebf7;border-radius:26px}h1{font-size:28px}a{display:block;background:#075f9f;color:white;text-align:center;border-radius:99px;padding:13px;text-decoration:none}p{color:#53697d}</style><main><h1>استوديو جسر الشرق</h1><p>دخول المالك لتعديل الموقع ومعاينته وحفظه في GitHub. لا يمكن لزوار الموقع حفظ أي تعديل.</p><a href="/api/auth/login">تسجيل الدخول عبر GitHub</a><p id="note"></p><script>if(new URLSearchParams(location.search).get('auth')==='failed')document.getElementById('note').textContent='تعذر الدخول. تأكد من الحساب المصرح، تثبيت التطبيق، Redirect URI ومتغيرات Netlify ثم أعد المحاولة.';</script></main></html>`;
export default handle(async(req,res)=>{const url=new URL(req.url,config.origin),action=url.searchParams.get('action')||'editor';if(action==='editor'&&req.method==='GET'){let s;try{s=session(req)}catch(e){if(!(e instanceof Failure&&e.status===401))throw e;res.setHeader('Content-Type','text/html; charset=utf-8');res.end(loginPage());return}await identity(s.token);res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: blob:; connect-src 'self'; frame-src 'self' https://www.google.com https://maps.google.com; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'");res.end(fs.readFileSync(editorFile(),'utf8'));return}
 const s=session(req);if(req.method==='POST')csrfCheck(req,s);await identity(s.token);
 if(action==='session'&&req.method==='GET'){json(res,200,{csrf:s.csrf,login:s.login});return}
 if(action==='load'&&req.method==='GET'){const sha=await head(s.token),snap=await snapshot(s.token,sha),bundle=await loadBundle(s.token,snap);json(res,200,{bundle,sha,csrf:s.csrf,login:s.login,media:references(bundle)});return}
 if(action==='media'&&req.method==='GET'){const sha=url.searchParams.get('sha')||'',pathValue=url.searchParams.get('path')||'';const filePath=mediaPath(pathValue),snap=await snapshot(s.token,sha),bytes=await readFile(s.token,snap,filePath,5*1024*1024);if(bytes.length>3*1024*1024)fail(413,'MEDIA_SIZE','الملف أكبر من حد المعاينة السحابية 3 ميجابايت.');const ext=pathValue.split('.').pop().toLowerCase(),type={pdf:'application/pdf',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp'}[ext];json(res,200,{path:pathValue,data:'data:'+type+';base64,'+bytes.toString('base64')});return}
 if(action==='save'&&req.method==='POST'){json(res,200,await saveBundle(s.token,await body(req)));return}fail(405,'METHOD','عملية أو طريقة طلب غير مدعومة.')});
